apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-{{ .Values.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: craigmiller160@gmail.com
    privateKeySecretRef:
      name: letsencrypt-{{ .Values.name }}
    solvers:
      - http01:
          ingress:
            class: public