{{- if .Values.name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-{{ $.Values.name }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
    {{- if .Values.backendIsHttps }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- end}}
    {{- if .Values.ipWhitelist }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ipWhitelist }}
    {{- end}}
spec:
  ingressClassName: public
  rules:
  {{- range $host := .Values.hosts }}
    - host: {{ $host.name }}
      http:
        paths:
          {{- range $service := $host.services}}
          - path: {{ $service.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $service.serviceName }}
                port:
                  number: {{ $service.portNumber }}
          {{- end}}
  {{- end }}
  tls:
    - secretName: {{ .Values.name }}-secret
      hosts:
      {{- range $host := .Values.hosts }}
        - {{ $host.name }}
      {{- end}}
{{- end }}